# environent-specific settings will be deep merged with the common hash, overriding values therein

common:
  providers:
    - twitter
    - open_id
    - google
    - yahoo
    - facebook
    - linked_in
    - github
    - foursquare
  auth_credentials:
    twitter:
      key: skeletonkey
      secret: seekrit!
    facebook:
      key: skeletonkey
      secret: seekrit!
    linked_in:
      key:
      secret: seekrit!
  google_analytics_id: <your id>
development:
  auth_credentials:
    github:
      key: developmentkey
      secret: devseekrit!
