# environent-specific settings will be deep merged with the common hash, overriding values therein

common:
  providers:
    - twitter
    - open_id
    - google
    - yahoo
    - facebook
    - linked_in
    - github
    - foursquare
  auth_credentials:
    twitter:
      key: skeletonkey
      secret: seekrit!
    facebook:
      key: skeletonkey
      secret: seekrit!
    linked_in:
      key:
      secret: seekrit!
  google_analytics_id: <your id>
  hoptoad: seekrit!
  secret_token: c63463de2c67e13400b5ee30329a12e6d95df8e7a24112c4420ceb0b540829cdcfa48cd1d54d9dff3cc89c552013cf9f5aab7dd2539291d9355bc2069367bafe
  organization:
    name: Org Name
    city: City
    state: State
    url: http://domain.org
    twitter: popular_tweeter
    email: admin@domain.org
    host: host
    host_url: host@domain.com
    logotype: <span>e</span>Logo
  search: sql
development:
  auth_credentials:
    github:
      key: developmentkey
      secret: devseekrit!
